title: Lumbo
author: Neeraj Bansal
email: neerajbansal54321@gmail.com
url: "https//lumbo.ca"
description: > # this means to ignore newlines until "baseurl:"
  Quarter Century old Engineering student who wants to understand and improve the society. I was born in India in 1996...

twitter_username: macrod68
github_username:  macrod68

sass:
    style: compressed